local wezterm = require "wezterm"
local act = wezterm.action

return {
  keys = {
    { key = "Tab", mods = "CTRL", action = act.ActivateTabRelative(1) },
    { key = "Tab", mods = "SHIFT|CTRL", action = act.ActivateTabRelative(-1) },
    { key = "Enter", mods = "ALT", action = act.ToggleFullScreen },
    {
      key = '"',
      mods = "SHIFT|CTRL",
      action = act.SplitHorizontal { domain = "CurrentPaneDomain" },
    },
    {
      key = "%",
      mods = "SHIFT|CTRL",
      action = act.SplitVertical { domain = "CurrentPaneDomain" },
    },
    { key = "C", mods = "CTRL", action = act.CopyTo "Clipboard" },
    { key = "F", mods = "CTRL", action = act.Search "CurrentSelectionOrEmptyString" },
    { key = "K", mods = "CTRL", action = act.ClearScrollback "ScrollbackOnly" },
    { key = "L", mods = "CTRL", action = act.ShowDebugOverlay },
    { key = "N", mods = "CTRL", action = act.SpawnWindow },
    { key = "P", mods = "CTRL", action = act.ActivateCommandPalette },
    { key = "R", mods = "CTRL", action = act.ReloadConfiguration },
    {
      key = "T",
      mods = "ALT",
      action = act.ShowLauncherArgs {
        flags = "FUZZY|LAUNCH_MENU_ITEMS|DOMAINS",
        title = "\u{f135}\u{20}\u{20}Search:",
      },
    },
    { key = "T", mods = "CTRL", action = act.SpawnTab "CurrentPaneDomain" },
    {
      key = "U",
      mods = "CTRL",
      action = act.CharSelect {
        copy_on_select = true,
        copy_to = "ClipboardAndPrimarySelection",
      },
    },
    { key = "V", mods = "CTRL", action = act.PasteFrom "Clipboard" },
    { key = "W", mods = "CTRL", action = act.CloseCurrentTab { confirm = true } },
    { key = "Z", mods = "CTRL", action = act.TogglePaneZoomState },
    { key = "c", mods = "LEADER", action = act.ActivateCopyMode },
    {
      key = "f",
      mods = "LEADER",
      action = act.ActivateKeyTable {
        name = "font_mode",
        one_shot = false,
        prevent_fallback = false,
        replace_current = false,
        until_unknown = false,
      },
    },
    { key = "h", mods = "ALT|CTRL", action = act.ActivatePaneDirection "Left" },
    {
      key = "h",
      mods = "LEADER",
      action = act.ActivateKeyTable {
        name = "help_mode",
        one_shot = true,
        prevent_fallback = false,
        replace_current = false,
        until_unknown = false,
      },
    },
    { key = "j", mods = "ALT|CTRL", action = act.ActivatePaneDirection "Down" },
    { key = "k", mods = "ALT|CTRL", action = act.ActivatePaneDirection "Up" },
    { key = "l", mods = "ALT|CTRL", action = act.ActivatePaneDirection "Right" },
    {
      key = "p",
      mods = "LEADER",
      action = act.ActivateKeyTable {
        name = "pick_mode",
        one_shot = true,
        prevent_fallback = false,
        replace_current = false,
        until_unknown = false,
      },
    },
    { key = "s", mods = "LEADER", action = act.Search "CurrentSelectionOrEmptyString" },
    {
      key = "w",
      mods = "LEADER",
      action = act.ActivateKeyTable {
        name = "window_mode",
        one_shot = false,
        prevent_fallback = false,
        replace_current = false,
        until_unknown = false,
      },
    },
    { key = "phys:Space", mods = "SHIFT|CTRL", action = act.QuickSelect },
    { key = "PageUp", mods = "NONE", action = act.ScrollByPage(-1) },
    { key = "PageDown", mods = "NONE", action = act.ScrollByPage(1) },
    { key = "Insert", mods = "CTRL", action = act.CopyTo "PrimarySelection" },
    { key = "Insert", mods = "SHIFT|CTRL", action = act.PasteFrom "PrimarySelection" },
    { key = "F1", mods = "SHIFT", action = act.ActivateTab(0) },
    { key = "F2", mods = "SHIFT", action = act.ActivateTab(1) },
    { key = "F3", mods = "SHIFT", action = act.ActivateTab(2) },
    { key = "F4", mods = "SHIFT", action = act.ActivateTab(3) },
    { key = "F5", mods = "SHIFT", action = act.ActivateTab(4) },
    { key = "F6", mods = "SHIFT", action = act.ActivateTab(5) },
    { key = "F7", mods = "SHIFT", action = act.ActivateTab(6) },
    { key = "F8", mods = "SHIFT", action = act.ActivateTab(7) },
    { key = "F9", mods = "SHIFT", action = act.ActivateTab(8) },
    { key = "F10", mods = "SHIFT", action = act.ActivateTab(9) },
    { key = "F11", mods = "SHIFT", action = act.ActivateTab(10) },
    { key = "F12", mods = "SHIFT", action = act.ActivateTab(11) },
    { key = "F13", mods = "SHIFT", action = act.ActivateTab(12) },
    { key = "F14", mods = "SHIFT", action = act.ActivateTab(13) },
    { key = "F15", mods = "SHIFT", action = act.ActivateTab(14) },
    { key = "F16", mods = "SHIFT", action = act.ActivateTab(15) },
    { key = "F17", mods = "SHIFT", action = act.ActivateTab(16) },
    { key = "F18", mods = "SHIFT", action = act.ActivateTab(17) },
    { key = "F19", mods = "SHIFT", action = act.ActivateTab(18) },
    { key = "F20", mods = "SHIFT", action = act.ActivateTab(19) },
    { key = "F21", mods = "SHIFT", action = act.ActivateTab(20) },
    { key = "F22", mods = "SHIFT", action = act.ActivateTab(21) },
    { key = "F23", mods = "SHIFT", action = act.ActivateTab(22) },
    { key = "F24", mods = "SHIFT", action = act.ActivateTab(23) },
  },

  key_tables = {
    copy_mode = {
      { key = "Tab", mods = "NONE", action = act.CopyMode "MoveForwardWord" },
      { key = "Tab", mods = "SHIFT", action = act.CopyMode "MoveBackwardWord" },
      { key = "Enter", mods = "NONE", action = act.CopyMode "MoveToStartOfNextLine" },
      { key = "Escape", mods = "NONE", action = act.CopyMode "Close" },
      { key = "$", mods = "SHIFT", action = act.CopyMode "MoveToEndOfLineContent" },
      { key = ",", mods = "NONE", action = act.CopyMode "JumpReverse" },
      { key = "0", mods = "NONE", action = act.CopyMode "MoveToStartOfLine" },
      { key = ";", mods = "NONE", action = act.CopyMode "JumpAgain" },
      {
        key = "F",
        mods = "NONE",
        action = act.CopyMode { JumpBackward = { prev_char = false } },
      },
      { key = "G", mods = "NONE", action = act.CopyMode "MoveToScrollbackBottom" },
      { key = "H", mods = "NONE", action = act.CopyMode "MoveToViewportTop" },
      { key = "L", mods = "NONE", action = act.CopyMode "MoveToViewportBottom" },
      { key = "M", mods = "NONE", action = act.CopyMode "MoveToViewportMiddle" },
      { key = "O", mods = "NONE", action = act.CopyMode "MoveToSelectionOtherEndHoriz" },
      {
        key = "T",
        mods = "NONE",
        action = act.CopyMode { JumpBackward = { prev_char = true } },
      },
      { key = "V", mods = "NONE", action = act.CopyMode { SetSelectionMode = "Line" } },
      { key = "^", mods = "NONE", action = act.CopyMode "MoveToStartOfLineContent" },
      { key = "b", mods = "NONE", action = act.CopyMode "MoveBackwardWord" },
      { key = "d", mods = "CTRL", action = act.CopyMode { MoveByPage = 0.5 } },
      { key = "e", mods = "NONE", action = act.CopyMode "MoveForwardWordEnd" },
      {
        key = "f",
        mods = "NONE",
        action = act.CopyMode { JumpForward = { prev_char = false } },
      },
      { key = "g", mods = "NONE", action = act.CopyMode "MoveToScrollbackTop" },
      { key = "h", mods = "NONE", action = act.CopyMode "MoveLeft" },
      { key = "j", mods = "NONE", action = act.CopyMode "MoveDown" },
      { key = "k", mods = "NONE", action = act.CopyMode "MoveUp" },
      { key = "l", mods = "NONE", action = act.CopyMode "MoveRight" },
      { key = "o", mods = "NONE", action = act.CopyMode "MoveToSelectionOtherEnd" },
      {
        key = "t",
        mods = "NONE",
        action = act.CopyMode { JumpForward = { prev_char = true } },
      },
      { key = "u", mods = "CTRL", action = act.CopyMode { MoveByPage = -0.5 } },
      { key = "v", mods = "NONE", action = act.CopyMode { SetSelectionMode = "Cell" } },
      { key = "v", mods = "CTRL", action = act.CopyMode { SetSelectionMode = "Block" } },
      { key = "w", mods = "NONE", action = act.CopyMode "MoveForwardWord" },
      {
        key = "y",
        mods = "NONE",
        action = act.Multiple {
          { CopyTo = "ClipboardAndPrimarySelection" },
          { CopyMode = "Close" },
        },
      },
      {
        key = "phys:Space",
        mods = "NONE",
        action = act.CopyMode { SetSelectionMode = "Cell" },
      },
    },

    font_mode = {
      { key = "Escape", mods = "NONE", action = act.PopKeyTable },
      { key = "+", mods = "NONE", action = act.IncreaseFontSize },
      { key = "-", mods = "NONE", action = act.DecreaseFontSize },
      { key = "0", mods = "NONE", action = act.ResetFontSize },
    },

    help_mode = {
      { key = "Tab", mods = "CTRL", action = act.ActivateTabRelative(1) },
      { key = "Tab", mods = "SHIFT|CTRL", action = act.ActivateTabRelative(-1) },
      { key = "Escape", mods = "NONE", action = act.PopKeyTable },
      {
        key = '"',
        mods = "SHIFT|CTRL",
        action = act.SplitHorizontal { domain = "CurrentPaneDomain" },
      },
      {
        key = "%",
        mods = "SHIFT|CTRL",
        action = act.SplitVertical { domain = "CurrentPaneDomain" },
      },
      { key = "C", mods = "CTRL", action = act.CopyTo "Clipboard" },
      { key = "F", mods = "CTRL", action = act.Search "CurrentSelectionOrEmptyString" },
      { key = "K", mods = "CTRL", action = act.ClearScrollback "ScrollbackOnly" },
      { key = "L", mods = "CTRL", action = act.ShowDebugOverlay },
      { key = "N", mods = "CTRL", action = act.SpawnWindow },
      { key = "P", mods = "CTRL", action = act.ActivateCommandPalette },
      { key = "R", mods = "CTRL", action = act.ReloadConfiguration },
      { key = "T", mods = "CTRL", action = act.SpawnTab "CurrentPaneDomain" },
      {
        key = "U",
        mods = "CTRL",
        action = act.CharSelect {
          copy_on_select = true,
          copy_to = "ClipboardAndPrimarySelection",
        },
      },
      { key = "V", mods = "CTRL", action = act.PasteFrom "Clipboard" },
      { key = "W", mods = "CTRL", action = act.CloseCurrentTab { confirm = true } },
      { key = "Z", mods = "CTRL", action = act.TogglePaneZoomState },
      { key = "c", mods = "LEADER", action = act.ActivateCopyMode },
      {
        key = "f",
        mods = "LEADER",
        action = act.ActivateKeyTable {
          name = "font_mode",
          one_shot = false,
          prevent_fallback = false,
          replace_current = false,
          until_unknown = false,
        },
      },
      { key = "h", mods = "ALT|CTRL", action = act.ActivatePaneDirection "Left" },
      {
        key = "h",
        mods = "LEADER",
        action = act.ActivateKeyTable {
          name = "help_mode",
          one_shot = true,
          prevent_fallback = false,
          replace_current = false,
          until_unknown = false,
        },
      },
      { key = "j", mods = "ALT|CTRL", action = act.ActivatePaneDirection "Down" },
      { key = "k", mods = "ALT|CTRL", action = act.ActivatePaneDirection "Up" },
      { key = "l", mods = "ALT|CTRL", action = act.ActivatePaneDirection "Right" },
      { key = "s", mods = "LEADER", action = act.Search "CurrentSelectionOrEmptyString" },
      {
        key = "w",
        mods = "LEADER",
        action = act.ActivateKeyTable {
          name = "window_mode",
          one_shot = false,
          prevent_fallback = false,
          replace_current = false,
          until_unknown = false,
        },
      },
      { key = "phys:Space", mods = "SHIFT|CTRL", action = act.QuickSelect },
      { key = "PageUp", mods = "NONE", action = act.ScrollByPage(-1) },
      { key = "PageDown", mods = "NONE", action = act.ScrollByPage(1) },
      { key = "Insert", mods = "CTRL", action = act.CopyTo "PrimarySelection" },
      { key = "Insert", mods = "SHIFT|CTRL", action = act.PasteFrom "PrimarySelection" },
    },

    pick_mode = {
      { key = "Escape", mods = "NONE", action = act.PopKeyTable },
      { key = "b", mods = "NONE", action = act.EmitEvent "user-defined-4" },
      { key = "c", mods = "NONE", action = act.EmitEvent "user-defined-0" },
      { key = "f", mods = "NONE", action = act.EmitEvent "user-defined-1" },
      { key = "l", mods = "NONE", action = act.EmitEvent "user-defined-3" },
      { key = "s", mods = "NONE", action = act.EmitEvent "user-defined-2" },
    },

    search_mode = {
      { key = "Escape", mods = "NONE", action = act.CopyMode "Close" },
      { key = "N", mods = "CTRL", action = act.CopyMode "PriorMatch" },
      { key = "n", mods = "CTRL", action = act.CopyMode "NextMatch" },
      { key = "r", mods = "CTRL", action = act.CopyMode "CycleMatchType" },
      { key = "u", mods = "CTRL", action = act.CopyMode "ClearPattern" },
      { key = "PageUp", mods = "NONE", action = act.CopyMode "PriorMatchPage" },
      { key = "PageDown", mods = "NONE", action = act.CopyMode "NextMatchPage" },
      { key = "UpArrow", mods = "NONE", action = act.CopyMode "PriorMatch" },
      { key = "DownArrow", mods = "NONE", action = act.CopyMode "NextMatch" },
    },

    window_mode = {
      { key = "Escape", mods = "NONE", action = act.PopKeyTable },
      { key = "+", mods = "NONE", action = act.AdjustPaneSize { "Up", 2 } },
      { key = "-", mods = "NONE", action = act.AdjustPaneSize { "Down", 2 } },
      { key = "<", mods = "NONE", action = act.AdjustPaneSize { "Left", 2 } },
      { key = ">", mods = "SHIFT", action = act.AdjustPaneSize { "Right", 2 } },
      { key = "h", mods = "NONE", action = act.ActivatePaneDirection "Left" },
      { key = "j", mods = "NONE", action = act.ActivatePaneDirection "Down" },
      { key = "k", mods = "NONE", action = act.ActivatePaneDirection "Up" },
      { key = "l", mods = "NONE", action = act.ActivatePaneDirection "Right" },
      { key = "o", mods = "NONE", action = act.TogglePaneZoomState },
      {
        key = "p",
        mods = "NONE",
        action = act.PaneSelect {
          alphabet = "",
          mode = "Activate",
          show_pane_ids = false,
        },
      },
      { key = "q", mods = "NONE", action = act.CloseCurrentPane { confirm = true } },
      {
        key = "s",
        mods = "NONE",
        action = act.SplitVertical { domain = "CurrentPaneDomain" },
      },
      {
        key = "v",
        mods = "NONE",
        action = act.SplitHorizontal { domain = "CurrentPaneDomain" },
      },
      {
        key = "x",
        mods = "NONE",
        action = act.PaneSelect {
          alphabet = "",
          mode = "SwapWithActive",
          show_pane_ids = false,
        },
      },
      { key = "LeftArrow", mods = "NONE", action = act.ActivatePaneDirection "Left" },
      { key = "RightArrow", mods = "NONE", action = act.ActivatePaneDirection "Right" },
      { key = "UpArrow", mods = "NONE", action = act.ActivatePaneDirection "Up" },
      { key = "DownArrow", mods = "NONE", action = act.ActivatePaneDirection "Down" },
    },
  },
}
